import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChakraProviderWrapper from "./components/ChakraProviderWrapper";
import NavBar from "./components/NavBar";
import ContextProvider from "./components/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dream Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <ChakraProviderWrapper>
            <NavBar></NavBar>
            {children}
          </ChakraProviderWrapper>
        </ContextProvider>
      </body>
    </html>
  );
}
